Resources:
  DocsBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.bucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
  DocAtlasBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.atlastBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
  DocAtlasOsbBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.atlasOsbBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
  DocAtlasGovBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.atlasGovBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
  DevhubBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.devhubBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html
  NewDevhubBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: developer-hub-prd
      WebsiteConfiguration:
          IndexDocument: index.html

  CloudManagerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.cloudManagerBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  OpsManagerBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: ${self:custom.opsManagerBucketName}
      WebsiteConfiguration:
          IndexDocument: index.html

  DocsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocsBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: 
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DocsBucket", "Arn" ] }, '/*']]

  DocAtlasBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocAtlasBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: 
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DocAtlasBucket", "Arn" ] }, '/*']]

  DocAtlasOsbBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocAtlasOsbBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: 
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DocAtlasOsbBucket", "Arn" ] }, '/*']]

  DocAtlasGovBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DocAtlasGovBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DocAtlasGovBucket", "Arn" ] }, '/*']]

  DevhubBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: DevhubBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: 
            - Fn::Join: ['', [{ "Fn::GetAtt": ["DevhubBucket", "Arn" ] }, '/*']]

  NewDevhubBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: NewDevhubBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["NewDevhubBucket", "Arn" ] }, '/*']]

  CloudManagerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: CloudManagerBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["CloudManagerBucket", "Arn" ] }, '/*']]

  OpsManagerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: OpsManagerBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
            - Fn::Join: ['', [{ "Fn::GetAtt": ["OpsManagerBucket", "Arn" ] }, '/*']]