service: docs-worker-pool
variablesResolutionMode: 20210326
plugins:
  - serverless-pseudo-parameters
provider:
  name: aws
  stage: ${opt:stage, 'stg'}
  deploymentBucket: ${self:custom.deploymentBucket.${opt:stage, 'stg'}}
  deploymentPrefix: serverless
  region: us-east-2
  vpc:
    securityGroupIds:
      - 'Fn::GetAtt':
          - GroupId
    subnetIds:
      - subnet-8c3623f6
      - subnet-a4ac73cf
      - subnet-9e83fed2
custom:
  deploymentBucket:
    intgr: workerpool-deployment
    stg: workerpool-deployment
    prd: workerpool-deployment
    dev: worker-pool-deployment
  ecs:
    port: '80'
    imageUrl: ${self:custom.accountId.${self:provider.stage}}.dkr.ecr.us-east-2.amazonaws.com/${self:service}-${self:provider.stage}:latest
    containerCpu:
      dev: '512'
      intgr: '512'
      stg: '2048'
      prd: '2048'
    containerMemory:
      dev: '1024'
      intgr: '1024'
      stg: '4096'
      prd: '4096'
    desiredCount:
      dev: 1
      intgr: '1'
      stg: '1'
      prd: '2' 
    minimumHealthyPercent:
      dev: 0
      intgr: 0
      stg: 0
      prd: 0
    maximumPercent:
      dev: 100
      intgr: 100
      stg: 100
      prd: 100
    deregistrationDelaySecs: '10'
  targetGroupName: docs-worker-pool
  accountId:
    dev: 216656347858
    stg: 216656347858
    intgr: 216656347858
    prd: 216656347858
  dbUsername: ${ssm:/env/${self:provider.stage}/docs/worker_pool/atlas/username}
  dbPassword: ${ssm:/env/${self:provider.stage}/docs/worker_pool/atlas/password}
  dbName: ${ssm:/env/${self:provider.stage}/docs/worker_pool/atlas/collection}
  awsKey: ${ssm:/env/${self:provider.stage}/docs/worker_pool/aws/key}
  awsSecret: ${ssm:/env/${self:provider.stage}/docs/worker_pool/aws/secret}
  githubBotUserName: ${ssm:/env/${self:provider.stage}/docs/worker_pool/github/bot/username}
  githubBotPW: ${ssm:/env/${self:provider.stage}/docs/worker_pool/github/bot/password}
  fastlyToken: ${ssm:/env/${self:provider.stage}/docs/worker_pool/fastly/token}
  fastlyDochubMap: ${ssm:/env/${self:provider.stage}/docs/worker_pool/fastly/dochub_map}
  fastlyServiceId: ${ssm:/env/${self:provider.stage}/docs/worker_pool/fastly/service_id}
  bucketName: docs-mongodb-org-${self:provider.stage}


resources:
  - ${file(./buckets.yml)}
  - ${file(./ecs_service.yml)}

