on:
  push:
    branches-ignore:
      - "master"
name: Deploy dev branch
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create ECS Repo
        run: |
          cd infrastructure/ecs-repo
          npm install
          sls deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          IMAGE_TAG: ${{ github.sha }}
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: docs-worker-pool-dev
          tags: latest, ${{ github.sha }}
          registry: 216656347858.dkr.ecr.us-east-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy ECS  
        working-directory: infrastructure/ecs-main
        run: |
          cd infrastructure/ecs-main
          npm install
          sls deploy --stage dev


