on:
  push:
    branches-ignore:
      - "master"
name: Deploy dev branch
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Create ECS Repo
        run: |
          cd infrastructure/ecs-repo
          npm install
          sls deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          IMAGE_TAG: ${{ github.sha }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Build and publish to ECR
        run: |
          docker build -f Dockerfile -t docs-worker-pool-task-dev:$IMAGE_TAG .
          docker tag docs-worker-pool-task-dev:$IMAGE_TAG 216656347858.dkr.ecr.us-east-2.amazonaws.com/docs-worker-pool-task-intgr-dev:$IMAGE_TAG
          docker tag docs-worker-pool-task-dev:$IMAGE_TAG 216656347858.dkr.ecr.us-east-2.amazonaws.com/docs-worker-pool-task-intgr-dev:latest
          docker push 216656347858.dkr.ecr.us-east-2.amazonaws.com/docs-worker-pool-task-intgr-dev:$IMAGE_TAG
          docker push 216656347858.dkr.ecr.us-east-2.amazonaws.com/docs-worker-pool-task-intgr-dev:latest
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: docs-worker-pool-service-ecr
          IMAGE_TAG: ${{ github.sha }}
      - name: Deploy ECS  
        working-directory: infrastructure/ecs-main
        run: |
          cd infrastructure/ecs-main
          npm install
          sls deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          IMAGE_TAG: ${{ github.sha }}


