on:
  push:
    branches-ignore:
      - "master"
name: Deploy integration branch
jobs:
  deploy-intgr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Create ECS Repo
        run: |
          cd infrastructure/ecs-repo
          npm install
          sls deploy --stage intgr
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: build and push to ECR
        with:
          image: docs-worker-pool-intgr
          tags: latest
          registry: 216656347858.dkr.ecr.us-east-2.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy ECS
        run: |
          cd infrastructure/ecs-main
          npm install
          sls deploy --stage intgr
          aws ecs update-service --force-new-deployment --service docs-worker-pool-intgr --cluster docs-worker-pool-intgr

